name: Cache Dependencies Workflow

on:
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: prime-cache-8b54c36
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-8b54c36

      - name: Show cache result
        run: |
          if [ -n "${{ steps.cache-step.outputs.cache-hit }}" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi
